import React, { useState } from 'react';
import {
  Zap,
  Moon,
  Sun,
  Clock,
  Calendar,
  Layers,
  Thermometer,
  Wind,
  Gauge,
  Activity,
  CheckCircle,
  HelpCircle,
  TrendingUp,
  AlertTriangle,
  UploadCloud,
  Cpu,
} from 'lucide-react';
import {
  ResponsiveContainer,
  ComposedChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
  Legend,
  ReferenceLine,
  ReferenceDot,
  Area,
} from 'recharts';
import { ForecastResponse } from '../types';
import { useCountUp } from './visuals';

interface ForecastResultProps {
  result: ForecastResponse;
}

export const ForecastResult: React.FC<ForecastResultProps> = ({ result }) => {
  const [chartMetric, setChartMetric] = useState<'irradiance' | 'power' | 'temperature' | 'wind'>('irradiance');

  const { prediction, diagnostics, weather_sequence, plant_metadata, plant_info, is_simulated, simulation_reason, power_source } = result;
  const isNightMasked = prediction.night_masked;
  const powerKw = prediction.power_kw;
  const animatedPowerKw = useCountUp(powerKw, 900);
  const nominalCapacityKw = (plant_metadata?.nominal_power_mw || plant_info?.nominal_power_mw || 0) * 1000;

  // Format timestamps
  const targetDate = new Date(prediction.target_datetime);
  const formattedTargetTime = !isNaN(targetDate.getTime())
    ? targetDate.toLocaleString(undefined, {
        weekday: 'short',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
        timeZoneName: 'short',
      })
    : prediction.target_datetime;

  // Prepare chart data from 192 weather sequence points
  const chartData = weather_sequence.map((row, idx) => {
    const d = new Date(row.datetime);
    const timeLabel = !isNaN(d.getTime())
      ? d.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
      : `t-${192 - idx}`;

    return {
      index: idx,
      datetime: row.datetime,
      label: timeLabel,
      normalized_power: row.total_active_power_w,
      poa: row.poa_irradiance_wm2,
      ghi: row.ghi_irradiance_wm2,
      ambient_temp: row.ambient_temperature_celsius,
      panel_temp: row.panel_temperature_celsius,
      wind_speed: row.wind_speed_ms,
    };
  });

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {/* Fix Issue #3: Loudly Visible Simulation Banner */}
      {is_simulated && (
        <div className="p-4 rounded-2xl bg-solar-950/50 backdrop-blur-md border border-solar-500/60 flex items-start space-x-3.5 text-solar-200 shadow-lg shadow-solar-950/40">
          <div className="p-2 rounded-xl bg-solar-500/20 text-solar-400 shrink-0">
            <AlertTriangle className="h-5 w-5" />
          </div>
          <div className="space-y-1">
            <div className="flex items-center space-x-2">
              <h4 className="text-sm font-bold text-solar-300">Simulated Prediction Fallback Active</h4>
              <span className="text-[10px] uppercase font-mono font-bold px-2 py-0.5 rounded bg-solar-500/20 text-solar-300 border border-solar-500/40">
                Offline Mode
              </span>
            </div>
            <p className="text-xs text-solar-200/90 leading-relaxed">
              This prediction was generated by the proxy's internal physics simulator because the external ML Model API was not connected.
              {simulation_reason && (
                <span className="block mt-1 font-mono text-[11px] text-solar-300">
                  Reason: <code>{simulation_reason}</code>
                </span>
              )}
            </p>
          </div>
        </div>
      )}

      {/* 1. Main Headline Forecast Card */}
      <div className="relative overflow-hidden bg-gradient-to-b from-slate-900/50 via-slate-900/50 to-slate-950/50 backdrop-blur-md border border-slate-800 rounded-3xl p-6 sm:p-8 shadow-2xl">
        {/* Glow accent */}
        <div className="absolute top-0 right-0 -mr-16 -mt-16 w-64 h-64 bg-solar-500/10 rounded-full blur-3xl pointer-events-none" />

        <div className="relative z-10 grid grid-cols-1 lg:grid-cols-3 gap-6 items-center">
          {/* Prominent Power Display */}
          <div className="lg:col-span-2 space-y-3">
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-[11px] uppercase tracking-widest font-bold text-solar-400 bg-solar-500/10 px-3 py-1 rounded-full border border-solar-500/20">
                24-Hour Ahead Prediction
              </span>
              {/* Fix Issue #5: Power source badge */}
              <span className={`text-[10px] px-2.5 py-1 rounded-full font-medium border ${
                power_source === 'user_uploaded'
                  ? 'bg-flux-500/10 text-flux-400 border-flux-500/20'
                  : 'bg-slate-800 text-slate-300 border-slate-700'
              }`}>
                Power Input: {power_source === 'user_uploaded' ? 'Uploaded History' : 'Physics Estimated (Fix #1)'}
              </span>
              {diagnostics.interpolated && (
                <span className="text-[10px] text-sky-400 bg-sky-500/10 px-2.5 py-1 rounded-full border border-sky-500/20">
                  Linear Interpolated
                </span>
              )}
            </div>

            <div className="flex items-center gap-4 sm:gap-5">
              <div className="flex items-baseline space-x-3">
                <h1 className="text-5xl sm:text-6xl font-extrabold tracking-tight text-white font-mono tabular-nums">
                  {animatedPowerKw.toLocaleString(undefined, { minimumFractionDigits: 1, maximumFractionDigits: 2 })}
                </h1>
                <span className="text-2xl font-bold text-solar-400 font-sans">kW</span>
              </div>
            </div>

            <div className="flex flex-wrap items-center gap-4 text-xs text-slate-400 pt-1">
              <div className="flex items-center space-x-1.5 bg-slate-950/50 px-3 py-1.5 rounded-lg border border-slate-800">
                <Clock className="h-4 w-4 text-solar-400" />
                <span>Forecast Target:</span>
                <strong className="text-slate-200 font-mono">{formattedTargetTime}</strong>
              </div>
              <div className="flex items-center space-x-1.5 bg-slate-950/50 px-3 py-1.5 rounded-lg border border-slate-800">
                <Calendar className="h-4 w-4 text-solar-400" />
                <span>Sequence End:</span>
                <span className="text-slate-200 font-mono">
                  {new Date(diagnostics.end_time).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                </span>
              </div>
            </div>
          </div>

          {/* Plant Summary / Structure Pill */}
          <div className="bg-slate-950/50 border border-slate-800 rounded-2xl p-4 sm:p-5 space-y-3">
            <h3 className="text-xs font-semibold text-slate-400 uppercase tracking-wider">
              Plant Configuration
            </h3>
            <div className="space-y-2 text-xs">
              <div className="flex justify-between">
                <span className="text-slate-400">Structure:</span>
                <span className="font-semibold text-solar-300">
                  {plant_metadata?.structure_type || plant_info?.structure_type || (diagnostics.is_tracker ? 'TRACKER' : 'FIXED')}
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Nominal Capacity:</span>
                <span className="font-semibold text-white">
                  {(plant_metadata?.nominal_power_mw || plant_info?.nominal_power_mw || 0)} MW
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Panels / Efficiency:</span>
                <span className="font-semibold text-white">
                  {(plant_metadata?.number_of_panels || plant_info?.number_of_panels || 0).toLocaleString()} ·{' '}
                  {(plant_metadata?.panel_efficiency_percentage || plant_info?.panel_efficiency_percentage || 0)}%
                </span>
              </div>
              <div className="flex justify-between">
                <span className="text-slate-400">Location / State:</span>
                <span className="font-semibold text-slate-200">
                  {plant_metadata?.state_name || plant_info?.state_name || 'Brazil'}
                </span>
              </div>
            </div>
          </div>
        </div>

        {/* 2. Night Masked Notice */}
        {isNightMasked && (
          <div className="mt-6 p-4 rounded-2xl bg-dusk-950/50 backdrop-blur-md border border-dusk-700/50 flex items-start space-x-3.5 text-dusk-200 animate-in fade-in duration-300">
            <div className="p-2 rounded-xl bg-dusk-900/50 text-dusk-300 shrink-0">
              <Moon className="h-5 w-5" />
            </div>
            <div className="space-y-1">
              <div className="flex items-center space-x-2">
                <h4 className="text-sm font-bold text-white">Nighttime Solar Masking Active</h4>
                <span className="text-[10px] uppercase font-bold px-2 py-0.5 rounded bg-dusk-500/20 text-dusk-300">
                  Solar Elevation ≤ 0°
                </span>
              </div>
              <p className="text-xs text-dusk-300/90 leading-relaxed">
                The 24-hour ahead prediction falls during local astronomical night hours. The system has properly masked
                the forecast to <strong>0.0 kW</strong>. This reflects physical solar absence and is normal operation.
              </p>
            </div>
          </div>
        )}
      </div>

      {/* 3. Interactive 48-Hour Historical Pipeline Visualization */}
      <div className="bg-slate-900/50 backdrop-blur-md border border-slate-800 rounded-3xl p-6 sm:p-8 shadow-2xl space-y-5">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-800/80 pb-4">
          <div>
            <div className="flex items-center space-x-2">
              <TrendingUp className="h-5 w-5 text-solar-400" />
              <h3 className="text-base font-bold text-white">48-Hour Weather Sequence & 24h Prediction Target</h3>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              192 historical 15-minute observations processed via pvlib transposition feeding into the ML model
            </p>
          </div>

          {/* Metric Selector Tabs */}
          <div className="flex bg-slate-950/50 p-1 rounded-xl border border-slate-800 text-xs self-start sm:self-auto">
            <button
              onClick={() => setChartMetric('irradiance')}
              className={`px-3 py-1.5 rounded-lg font-medium transition-all duration-200 press-feedback ${
                chartMetric === 'irradiance' ? 'bg-solar-500 text-slate-950 font-bold' : 'text-slate-400 hover:text-white hover:bg-slate-800/60'
              }`}
            >
              POA vs GHI
            </button>
            <button
              onClick={() => setChartMetric('power')}
              className={`px-3 py-1.5 rounded-lg font-medium transition-all duration-200 press-feedback ${
                chartMetric === 'power' ? 'bg-solar-500 text-slate-950 font-bold' : 'text-slate-400 hover:text-white hover:bg-slate-800/60'
              }`}
            >
              Normalized Power
            </button>
            <button
              onClick={() => setChartMetric('temperature')}
              className={`px-3 py-1.5 rounded-lg font-medium transition-all duration-200 press-feedback ${
                chartMetric === 'temperature' ? 'bg-solar-500 text-slate-950 font-bold' : 'text-slate-400 hover:text-white hover:bg-slate-800/60'
              }`}
            >
              Temperatures
            </button>
            <button
              onClick={() => setChartMetric('wind')}
              className={`px-3 py-1.5 rounded-lg font-medium transition-all duration-200 press-feedback ${
                chartMetric === 'wind' ? 'bg-solar-500 text-slate-950 font-bold' : 'text-slate-400 hover:text-white hover:bg-slate-800/60'
              }`}
            >
              Wind Speed
            </button>
          </div>
        </div>

        {/* Recharts Component */}
        <div className="h-72 sm:h-80 w-full pt-2">
          <ResponsiveContainer width="100%" height="100%">
            <ComposedChart data={chartData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
              <defs>
                <linearGradient id="poaGradient" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#f59e0b" stopOpacity={0.4} />
                  <stop offset="95%" stopColor="#f59e0b" stopOpacity={0.0} />
                </linearGradient>
                <linearGradient id="powerGradient" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#10b981" stopOpacity={0.4} />
                  <stop offset="95%" stopColor="#10b981" stopOpacity={0.0} />
                </linearGradient>
                <linearGradient id="panelTempGradient" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="5%" stopColor="#ef4444" stopOpacity={0.3} />
                  <stop offset="95%" stopColor="#ef4444" stopOpacity={0.0} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
              <XAxis
                dataKey="label"
                stroke="#64748b"
                tick={{ fontSize: 10, fill: '#64748b' }}
                interval={23}
              />
              <YAxis stroke="#64748b" tick={{ fontSize: 10, fill: '#64748b' }} />
              <Tooltip
                contentStyle={{
                  backgroundColor: '#0f172a',
                  borderColor: '#334155',
                  borderRadius: '0.75rem',
                  fontSize: '12px',
                  color: '#f8fafc',
                }}
              />
              <Legend wrapperStyle={{ fontSize: '11px', paddingTop: '10px' }} />

              {/* Irradiance Lines */}
              {chartMetric === 'irradiance' && (
                <>
                  <Area
                    type="monotone"
                    dataKey="poa"
                    name="POA Irradiance (pvlib W/m²)"
                    stroke="#f59e0b"
                    strokeWidth={2}
                    fillOpacity={1}
                    fill="url(#poaGradient)"
                  />
                  <Line
                    type="monotone"
                    dataKey="ghi"
                    name="GHI Irradiance (Open-Meteo W/m²)"
                    stroke="#38bdf8"
                    strokeWidth={1.5}
                    strokeDasharray="4 4"
                    dot={false}
                  />
                </>
              )}

              {/* Normalized Power Line (Fix Issue #1) */}
              {chartMetric === 'power' && (
                <Area
                  type="monotone"
                  dataKey="normalized_power"
                  name="Normalized Active Power (total_active_power_w [0,1])"
                  stroke="#10b981"
                  strokeWidth={2}
                  fill="url(#powerGradient)"
                />
              )}

              {/* Temperature Lines */}
              {chartMetric === 'temperature' && (
                <>
                  <Area
                    type="monotone"
                    dataKey="panel_temp"
                    name="Panel Temp (pvlib SAPM °C)"
                    stroke="#ef4444"
                    strokeWidth={2}
                    fill="url(#panelTempGradient)"
                  />
                  <Line
                    type="monotone"
                    dataKey="ambient_temp"
                    name="Ambient Air Temp (°C)"
                    stroke="#a855f7"
                    strokeWidth={1.5}
                    dot={false}
                  />
                </>
              )}

              {/* Wind Speed Line */}
              {chartMetric === 'wind' && (
                <Line
                  type="monotone"
                  dataKey="wind_speed"
                  name="Wind Speed (m/s)"
                  stroke="#10b981"
                  strokeWidth={2}
                  dot={false}
                />
              )}
            </ComposedChart>
          </ResponsiveContainer>
        </div>

        {/* 4. Sequence Stats and Verification Summary */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 pt-3 text-xs">
          <div className="interactive-tile p-3 bg-slate-950/50 rounded-xl border border-slate-800 hover:border-solar-500/30 hover:bg-slate-950/70 cursor-default">
            <span className="text-slate-400 block text-[11px]">Total Timesteps</span>
            <span className="font-mono font-bold text-white text-sm mt-0.5 block">
              {diagnostics.row_count} rows (48h @ 15m)
            </span>
          </div>
          <div className="interactive-tile p-3 bg-slate-950/50 rounded-xl border border-slate-800 hover:border-solar-500/30 hover:bg-slate-950/70 cursor-default">
            <span className="text-slate-400 block text-[11px]">Peak POA Irradiance</span>
            <span className="font-mono font-bold text-solar-400 text-sm mt-0.5 block">
              {diagnostics.max_poa} W/m²
            </span>
          </div>
          <div className="interactive-tile p-3 bg-slate-950/50 rounded-xl border border-slate-800 hover:border-solar-500/30 hover:bg-slate-950/70 cursor-default">
            <span className="text-slate-400 block text-[11px]">Peak Normalized Power</span>
            <span className="font-mono font-bold text-flux-400 text-sm mt-0.5 block">
              {diagnostics.max_normalized_power !== undefined ? diagnostics.max_normalized_power : 'N/A'}
            </span>
          </div>
          <div className="interactive-tile p-3 bg-slate-950/50 rounded-xl border border-slate-800 hover:border-solar-500/30 hover:bg-slate-950/70 cursor-default">
            <span className="text-slate-400 block text-[11px]">Transposition Model</span>
            <span className="font-mono font-bold text-sky-400 text-sm mt-0.5 block">
              {diagnostics.is_tracker ? 'pvlib Single-Axis' : 'pvlib Fixed-Tilt'}
            </span>
          </div>
        </div>
      </div>
    </div>
  );
};
